apiVersion: 1

datasources:
  - name: ParkGrid-Influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
    isDefault: true
